

name: gishtube
description: Netflix-styled video streaming app
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.8.2
  provider: ^6.1.2
  audioplayers: ^5.2.1
  http: ^1.2.0
  cached_network_image: ^3.3.1
  fluttertoast: ^9.0.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/default_poster.jpg
    - assets/TheRip_phto.jpeg
    - assets/LstHozn_phto.jpeg
    - assets/Aplace_wth_u_mphoto.jpeg
    - assets/Aride4evr_phto.jpg
    - assets/best_frnd_movie_photo.jpg
    - assets/Aftrburn_phto.jpeg
    - assets/kisofdspidrwmn_phto.jpeg
    - assets/gishtube_logo.png
    - assets/heswchn_uphto.jpeg
    - assets/vanshd_mv_phto.jpeg
    - assets/drm4lz_mvphto.jpeg
    - assets/frkiafrda_phto.jpeg
    - assets/spngbobmv_phto.jpeg
    - assets/1battlaftrdothr_phto.jpeg
    - assets/theintnshp_phto.jpeg
    - assets/audio/cinematic_intro.mp3
    - assets/privacy_policy.txt

# Flutter Launcher Icons
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"   # Make sure this file exists
