    
name: gishtube
description: Netflix styled video streaming app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Video
  video_player: ^2.8.2

  # UI & State
  provider: ^6.1.2

  # Audio
  audioplayers: ^5.2.1

  # Networking & images
  http: ^1.2.0
  cached_network_image: ^3.3.1

  # ✅ FIXED (new version)
  fluttertoast: ^9.0.0

  # Firebase (MODERN — REQUIRED)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/default_poster.jpg
    - assets/TheRip_phto.jpeg
    - assets/LstHozn_phto.jpeg
    - assets/Aplace_wth_u_mphoto.jpeg
    - assets/Aride4evr_phto.jpg
    - assets/best_frnd_movie_photo.jpg
    - assets/Aftrburn_phto.jpeg
    - assets/kisofdspidrwmn_phto.jpeg
    - assets/gishtube_logo.png

    # extra posters
    - assets/heswchn_uphto.jpeg
    - assets/vanshd_mv_phto.jpeg
    - assets/drm4lz_mvphto.jpeg
    - assets/frkiafrda_phto.jpeg
    - assets/spngbobmv_phto.jpeg
    - assets/1battlaftrdothr_phto.jpeg
    - assets/theintnshp_phto.jpeg

    # audio
    - assets/audio/cinematic_intro.mp3
